name: Flutter

on:
  push:
    branches: [ "flutterflow" ]
  pull_request:
    branches: [ "flutterflow" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Use the Flutter action to set up Flutter SDK instead of Dart SDK
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test 
